### ISSUE TITLE
Inventory hiba.

### ISSUE THREAD

**Issue by Heppi021** [hlgamesystem/hlmta_public#10]
### Írd le részletesen a hibát

A /elvesz fegyver parancs nem veszi el a playerektől a fegyver tárakat és gyanítom , hogy a golyókat sem. 

### Reprodukálás lépései

 Nem hiszem, hogy szükséges, fent leírtam mindent.

**Comment by Xenius97** [comment]
@JackLuciano  ötlet?

**Comment by JackLuciano** [comment]
Fegyvereket nagy esellyel azert mert skines, tarak loszerek meg nem lettek beleirva, azokat javitom mindjart.

**Comment by Heppi021** [comment]
Fegyverekkel nincs gond , elveszi és kiosztja a figyelmeztetést is , a tarakkal es golyokkalmvolt eddig a gond. Köszi.

**Comment by JackLuciano** [comment]
Ja bocsi, felreolvastam, tarakat loszereket meg most csinaltam meg, kovi updattel jon

**Comment by Heppi021** [comment]
Köszönjük!

**Comment by TheViko** [comment]
lőszer nem golyó

**Comment by Xenius97** [comment]
> lőszer nem golyó
> 

Golyóóóó
