### ISSUE TITLE
Duty percek.

### ISSUE THREAD

**Issue by Heppi021** [hlgamesystem/hlmta_public#11]
### Írd le részletesen a hibát

A dutypercek még most sem frissülnek kifagyásnál vagy kilépésnél írtam már kétszer fórumra. Tegnap két óra dutyzás után ma felnéztem 9 perc duty időt ír. 

### Reprodukálás lépései

1. Lépj be dutyba. 
2. Dutyzz 10 percet. 
3. Lépj ki / fagyj ki dutyba. 
4. Nem adja hozzá a dutyperceket.

**Comment by Xenius97** [comment]
https://forum.hl-rpg.eu/threads/dutyido-bug.57895/

**Comment by JackLuciano** [comment]
Kovetkezo updattel bekerul, majd teszteljetek.
