### ISSUE TITLE
Dashboard frakciók hiba.

### ISSUE THREAD

**Issue by Heppi021** [hlgamesystem/hlmta_public#13]
### Írd le részletesen a hibát

Bocsi, megint én :D . A /frakciok parancs eddig működott, most megnyitja a dashboard-ot de semmit nem dob ki. Ha hiba akkor jó helyre írtam ha kilett véve akkor sorry. 

### Reprodukálás lépései

Videóban látszani fog : https://imgur.com/a/W4564cd 
 A /frakciok parancsot írtam be , dashboardba az a fül teljesen el is tűnt nekem.

### Egyéb információk

-

**Comment by Xenius97** [comment]
Frakció lista ott van, csak a parancs dob rossz helyre

**Comment by JackLuciano** [comment]
Nem, ki lett veve, csak adminoknak elerheto jelenleg. Ujra lesz dolgozva es akkor visszakapjak majd a jatekosok.

**Comment by Heppi021** [comment]
> Frakció lista ott van, csak a parancs dob rossz helyre

![image](https://user-images.githubusercontent.com/118636839/203360600-d4fcbcc8-b869-4674-8892-caf107bc585e.png)

**Comment by JackLuciano** [comment]
A frakciok parancs az osszes frakcio megjelenitette es h mennyien vannak online
