### ISSUE TITLE
Inventory - Alkohol szonda , drogteszt.

### ISSUE THREAD

**Issue by Heppi021** [hlgamesystem/hlmta_public#16]
### Írd le részletesen a hibát

Elvileg már bekerült az utolsó frakció fejlesztési csomaggal az alkohol szonda illetve a drog teszt. FőAdmin szerint a itemlist-ben benne van mind a kettő, csak valahogyan nem lett hozzáadva a fegyverraktárhoz - duty itemek közé. 

### Reprodukálás lépései

Nem hiszem, hogy szükséges. Kíváncsi lennék, hogy működnek -e amennyiben igen akkor örülnénk ha bekerülne a fegyver raktárunkba, amennyiben nem akkor bocsi a felesleges topic nyitásért.

**Comment by Heppi021** [comment]
Szintén zárható. "Fel lett írva" - írta Xenius fórumon.

**Comment by Xenius97** [comment]
Másik naplóba fel van írva
