### ISSUE TITLE
Ticket hiba.

### ISSUE THREAD

**Issue by Heppi021** [hlgamesystem/hlmta_public#17]
### Írd le részletesen a hibát

Régi inventoryban ugyebár a ticket-et miután kiosztottuk ha nem fizették be az NPC-nél hét napig akkor levonta az összegnek a dupláját bankszámláról / kezéből. Most rengeteg olyan játékost motozunk meg akiknél pár hetes vagy akár hónapos csekk áll az inventoryjukba és nem vonja le őket a rendszer. 

### Reprodukálás lépései

Nem tudom , hogyan lehetne hatékonyan reprodukálni. 
 1. Oszd ki a csekket a /ticket parancsal. 
 2. Hét nap eltelte után nem von le semmilyen péznt.

### Egyéb információk

Eddig úgy működött hogy hét nap után miután bejelentkezett a player levonta a ticket összegének a dupláját ha nem fizette be.

**Comment by Xenius97** [comment]
Javítva
