### ISSUE TITLE
/lockcarshop parancs nem működik/nincs neki használati hely

### ISSUE THREAD

**Issue by Skeeeer** [hlgamesystem/hlmta_public#18]
/lockcarshop nem működik!

A /lockcarshop nem működik vagy nincs neki hely, kivették a kis $-jelet amibe bele állva lehetett lezárni/nyitni kereskedéseket, ez eltűnt így már nem tudok se nyitni, se zárni. Van kereskedés ami lezárva maradt és nem tudom megnyitni sehogy sem.

### Reprodukálás lépései

Nem fontos

### Egyéb információk

nincs

### Log

```shell
nincs
```

**Comment by Xenius97** [comment]
Megoldva, interioron belül használható
