### ISSUE TITLE
Dashboard mentés hiba.

### ISSUE THREAD

**Issue by Heppi021** [hlgamesystem/hlmta_public#20]
### Írd le részletesen a hibát

A dashboard megjelenítési beállításokat néha elmenti néha nem. Kifagyáskor például nekem egyszer sem mentette el. Kilépéskor pedig szintén nem mindig. Tegnap úgy léptem ki, hogy az összes játék grafikát modosító beállítás ki volt kapcsolva. Most ismét arra jöttem vissza, hogy kettő bekapcsolódott. A szerver beállítások fülön sem ment el semmit. 

### Reprodukálás lépései

1. Dashboardba állíts át valamit. 
2. Lépegess ki párszor a szerverről majd csatlakozz újra. 
3. Egy idő után vissza áll a default beállításokra. Visszakapcsolódik amit már kikapcsoltál.

**Comment by Heppi021** [comment]
Kitöröltem a JSON file-okat a gépemről ,amiket a HL mentett le. Azóta működik a mentés.

**Comment by JackLuciano** [comment]
Azota javitva
