### ISSUE TITLE
FBI helikopterek rossz helyre spawnolnak

### ISSUE THREAD

**Issue by tonycolt** [hlgamesystem/hlmta_public#21]
### Írd le részletesen a hibát

Az FBI épületénél San Fierróban rossz helyre spawnolnak a helikopterek. Naponta járok arra áruszállítóként és mindig valamelyik az út közepén áll, a másik pedig az épületben buggol. Biztosan hiba, mert tegnap egy másik helikopter állt ugyanitt.
Naponta kerülgetem őket.
### Reprodukálás lépései

https://imgur.com/yVCnzp8
https://imgur.com/i6KB07u

### Egyéb információk

Ne legyen ott :D

**Comment by eth3301** [comment]
MTA streaming hiba, ha valakinél nem tölt be a mappolt object akkor a helikopterek úgy viselkednek mintha nem lenne ott semmi, ezért kiesik a világból, és az útra dobja őket. Ugyanez megtörténik a kórháznál is. Egy automata freeze kéne helire ha levan állítva és kiszáll belőle a vezető.

**Comment by Xenius97** [comment]
Helyes megoldás:
freeze
/park

Mindig legyen freezelve és nem lesz ilyen gond
