### ISSUE TITLE
Achievement vállalkozást nem számolja

### ISSUE THREAD

**Issue by tonycolt** [hlgamesystem/hlmta_public#22]
### Írd le részletesen a hibát

Pár achievementet nem számol a rendszer.

### Reprodukálás lépései

Vállalkozó szellem/Legyen egy vállalkozásod küldetést nem számolja. Kipróbáltam, hogy eladom/visszaveszem és úgy sem.
Pörgess tízszer a szerencsekeréken szintén nem.

### Egyéb információk

Vállalkozás Bolt. Iroda 6028. Tulajdonos: Tony Colt

**Comment by Xenius97** [comment]
javítva, legkésőbb kövi update

**Comment by tonycolt** [comment]
> 

Meg is kaptam egyből. Köszi
