### ISSUE TITLE
Dashboard hiba.

### ISSUE THREAD

**Issue by Heppi021** [hlgamesystem/hlmta_public#28]
### Írd le részletesen a hibát

A tuningokat kis képernyős dashboardba elég csúnyán jeleníti meg. Kép : https://imgur.com/a/7rCH86r

 Illetve néhány autónak hiába tuningos egyáltalán nem tölti be a tuningjait, semmit nem ír ki róla. 

### Reprodukálás lépései

1. Képen látszik a probléma.

**Comment by JackLuciano** [comment]
Ki lesz veve a kis dashboard, jelenleg csak teszt jelleggel volt bent
