### ISSUE TITLE
Droglabor

### ISSUE THREAD

**Issue by PetoDominik** [hlgamesystem/hlmta_public#3]
### Írd le részletesen a hibát

Tegnapi nap folyamán a frakció tagok tudtak csinálni pár methet viszont ma már nem lehet semmit se csinálni mivel azt írja hogy az inventory tele van közben pedig nem.

### Reprodukálás lépései

1. Húzd rá mondjuk az efedrint a laborfelszerelésre
2. Majd egyből látod a hibát.

### Log

```shell
Logom nincs képet tudok küldeni
https://imgur.com/a/RIjtqPo
720 interior Center Park Boys a frakció amiben vagyunk.
```

**Comment by Xenius97** [comment]
Szia!
Amint a halloweeni eventnél kiderült, hamarosan teljesen új drogrendszer lesz így ez már nem lesz javítva. Azért köszi hogy jelezted. :)

**Comment by Xenius97** [comment]
Újranyitom, azt az infót kaptam hogy ez marad @JackLuciano

**Comment by bence444** [comment]
Következő updatere kap javítást + kis ráncfelvarrást a rendszer
