### ISSUE TITLE
Dodge Demon-on nem villog kéken a felrakható villogó.

### ISSUE THREAD

**Issue by Tibi5D** [hlgamesystem/hlmta_public#30]
### Írd le részletesen a hibát

Gondolom nincs beállítva rendesen erre az autóra a villogó, és így nem villog. (Dodge Demon)

Kép: https://imgur.com/a/5tMpFUl

### Reprodukálás lépései

-

### Egyéb információk

-

### Log

```shell
-
```

**Comment by Xenius97** [comment]
A felrakható villogónak mindig ott kell villognia ahol a villogó van, itt valószínűleg nem frissít rá
