### ISSUE TITLE
Achievement bugok

### ISSUE THREAD

**Issue by tonycolt** [hlgamesystem/hlmta_public#32]
### Írd le részletesen a hibát

Pár észrevétel lentebb.

### Reprodukálás lépései

1. Legyél fent éjfélkor számolja, de nem adja meg.
2. Pörgesd meg a szerencsekereket 10 alkalommal nem számolja.
3. Teljesíts 10 napi küldetést (heti) nem számolja.
4. Veszíts el a blackjacken 200.000 dollárt nem számolja

**Comment by Xenius97** [comment]
> Pörgesd meg a szerencsekereket 10 alkalommal nem számolja.

Ez a kaszinós kerékre vonatkozik, ami pénzzel működik

**Comment by tonycolt** [comment]
> > Pörgesd meg a szerencsekereket 10 alkalommal nem számolja.
> 
> Ez a kaszinós kerékre vonatkozik, ami pénzzel működik

**Comment by Xenius97** [comment]
Miért nyitottad újra?

**Comment by Xenius97** [comment]
Láttam hogy itt van ez is, ne pingeld feleslegesen ez is sorra fog kerülni :)

**Comment by tonycolt** [comment]
> Láttam hogy itt van ez is, ne pingeld feleslegesen ez is sorra fog kerülni :)

Véletlenül zártam le tegnap. Még szoknom kell. Bocsi. Nem direkt volt. Amúgy a bolt fontosabb lenne amúgy is, mert nemrég lett megcsinálva végre és most megint félig használhatatlan, de türelmes vagyok most ne aggódj. addig elvagyok az eventekkel. :)

**Comment by Xenius97** [comment]
Semmi gond. :)
