### ISSUE TITLE
Bankszámla bug

### ISSUE THREAD

**Issue by extaboi** [hlgamesystem/hlmta_public#34]
### Írd le részletesen a hibát

Amennyiben úgy dönt valaki ,hogy nem csak 1 számlát hoz létre ,akkor a többi számlán nem adja hozzá kamathoz tegyükfel az első számlámon van 5.000.000$ a második számlámon pedig 2.000.000$ ,akkor a kamatom 5.000$ lesz nem 7.000$ azaz többi számlát teljesen figyelmen kívül hagyja a rendszer ilyen szempontból.

### Reprodukálás lépései

1. Hozz létre legalább 2 bankszámlát.
2. Tölts fel a két számlára pénzt.
3. Következő adólevonáskor/fizetéskor csak az első számlán lévő összeget fogja figyelembe venni.

**Comment by Xenius97** [comment]
Mindig csak a legnagyobb számlán lévő összeg kamatozik a kezdetek óta, talán fórumon is feltüntettük annó már nem emlékszem.
