### ISSUE TITLE
Vállalkozás bolt problémák az új itemek miatt

### ISSUE THREAD

**Issue by tonycolt** [hlgamesystem/hlmta_public#36]
### Írd le részletesen a hibát

Sziasztok! Több problémát is jeleznék lentebb ami a frissítéssel és az új itemekkel érkezett.

bizonyítékok:
https://imgur.com/drdgRjY
https://imgur.com/sA9ElaZ
https://imgur.com/MD4iUOo
https://imgur.com/3Cl1wrS
https://imgur.com/wJrG5Dd
https://imgur.com/fxC8n97

### Reprodukálás lépései

1. Az új itemekből 8 darab már létezik a szerveren picikét más elnevezéssel. Keksz, Fánk, Hamburger, Hot-Dog, Jack Deniels, Pepsi Cola, Coca Cola, Fanta. Ez azért problémás, mert ha már tudok majd rendelni, nem tudom melyikből hiányzik a készletből, mert a kiszállításnál csak szöveg van, kép nincs. Megtévesztő nagyon! Ezekre elköltöttem 4000 HLP -t, mivel +1 item 500HLP -be kerül. Ha megszűnik a duplikáció szeretném visszakapni a PP -t.
2. Az új itemekből nem tudok rendelni, csak a régieket engedi. Így ezekből kiszállítani sem tudok.
3. A kiszállításoknál nem jelenik meg néhány kiszállítandó item neve, így nem is tudom mi hiányzik. Gondolom ezek az új itemek.
4. A bolt NPC -nél csak 32 darab item látható a 78 -ból (98). Görgetéskor befagy a lista többször is és csak relog segít.
### Egyéb információk

6027 -es bolt
6028 -as iroda

**Comment by Xenius97** [comment]
@JackLuciano mi okozhatja?

**Comment by JackLuciano** [comment]
Az okozza, h valamiert nem kap itemvaluet az fv es nem tudja szerintem lekerni az item nevet

**Comment by tonycolt** [comment]
Sziasztok! Így hogy kivettétek az új itemeket így minden ok, kivéve a 4. pontot. Még mindig csak 32 item van az NPC -nél, pedig 78 itemem van.

**Comment by tonycolt** [comment]
Update: Ha az NPC -nél rákeresek pl. a tüzijátékra, akkor megtalálja az itemek között, viszont szűrő nélkül csak az első 32 darab itemet lehet látni. Még egy probléma felmerült, hogy pl. ha csalit akarok venni és abból lehet több darabot is, akkor ha rákattintok nem történik semmi, de ha ki akarok lépni, csak akkor jelenik meg a felugró popup ablak, hogy mennyit szeretnék venni.
Valószínűleg mivel ezeknél az itemeknél alpból 0 a vételi szándék, emiatt nem működik. Szerintem alapértelmezetten ezeknél is lehetne, az 1 darab és így nem okozna problémát. Boltomban tesztelhető az NPC nél.
