### ISSUE TITLE
 Achievement hibabejelentés.

### ISSUE THREAD

**Issue by AndrisHU** [hlgamesystem/hlmta_public#37]
### Írd le részletesen a hibát

A hiba: Ugye van két darab  achievement (Támogasd a szerver, Vegyél Prémium Pontot), na hát velük lenne gond. Vettem 30.000HLP ami 20€-ba került. És mikor felléptem a szerverre nem kaptam meg az achievement-eket. Láttam hogy sok ember tapasztalta ezt a hibát. 

### Reprodukálás lépései

1. Vegyél PP-t.
2. Lépj fel a szerverre. 
3. És nem kaptam meg.
(Nekem ennyi történt.)

**Comment by Xenius97** [comment]
Mi a karakter id-d?

**Comment by Xenius97** [comment]
A hiba javítva lett

**Comment by AndrisHU** [comment]
Karakter ID: 320969
                    Oscar Roy

**Comment by Xenius97** [comment]
Megoldva
