### ISSUE TITLE
Egyirányúvá változott a farmom.

### ISSUE THREAD

**Issue by eth3301** [hlgamesystem/hlmta_public#4]
### Írd le részletesen a hibát

Ma délután megvételre került egy farm, jelenleg #5 id-vel.
Ha kint kinyitom, betudok menni de utána bentről nem tudok kimenni.
ha bent kinyitom, akkor kitudok menni, de utána nem tudok bemenni.

Szerintem ahoz van köze hogy úgy vettem a farmot hogy kinyitva volt, vagy fordítva.
Többi frissen vásárolt farmom is ezzel szenved.

https://user-images.githubusercontent.com/70336188/200062718-a20e3545-3582-4f9d-8c0d-d7c81873974f.mp4

### Reprodukálás lépései

Kerüljön automata eladásra egy kinyitott, illetve becsukott állapotba lévő farm.
Utána elő kell jönnie valamelyiknek.

**Comment by Xenius97** [comment]
Gyanítom, hogy azért nem megy mert a marker sem látszik kint.

**Comment by eth3301** [comment]
> Gyanítom, hogy azért nem megy mert a marker sem látszik kint.

Az összes eladóvá vált farm markere eltűnt, mikor eladó volt akkor is el volt tűnve, illetve amikor megvettem akkor is. Például a következő farmnál tökéletesen megy a nyitás/zárás markerje pedig nincs. Az egy másik hiba lesz. (#216)

https://user-images.githubusercontent.com/70336188/200077803-9ead140b-8303-45cd-b600-a291f3a7120b.mp4

**Comment by Xenius97** [comment]
Megoldódott?

**Comment by Xenius97** [comment]
Visszajelzés hiányában zárom
