### ISSUE TITLE
Nem lehet stackelni a gombát, jointot. 

### ISSUE THREAD

**Issue by Laszloobcxvbybdfg** [hlgamesystem/hlmta_public#41]
### Írd le részletesen a hibát

1. Ráhúzom és nem rakja össze, pedig összerakva kaptam meg. Ebbe a témába már írtak ugyan erről és videó is látható, ugyan ez van nálam. https://forum.hl-rpg.eu/threads/inventory-bug.56191/

2. Meal4home futárkodásnál meg pl van nálam 3 gomba stackelve azt írja Josh hogy 1/3 van nálad csak. Szét kell szedni 3 fele és úgy már jó, stackelve nem 3-nak érzékeli. https://i.imgur.com/VALoNT0.png
(itt látható hogy 3 volt stackelve: https://i.imgur.com/HIOD01O.png)

3. Sokszor elvész a kordináta GPS által ha olyan helyen indítom ahol nincs út és bedöglik egyből a GPS, de van hogy egyből kapásból elvész a GPS jel és nem tudom hova kell vinni így a fuvar megfelelő lenne viszont az összes post végig kell járni amég meg nem találom. Jó lenne egy olyan gomb erre hogy "kordináta újratöltése" a telóba. 

4. A jointot nem lehet szétszedni, jó lenne ha vissza szét lehetne szedni mariskává. 

### Reprodukálás lépései

Mindent leírtam

**Comment by JackLuciano** [comment]
1. Mivel majdnem minden drognak sajat sulya van ezert nem lehet osszerakni. Ami ossze van rakva azokat szet lehet szedni.
2. Direkt van igy megcsinalva.
3. Ez nem a meal4home hanem a gps baja
4. Ird be forumon javaslatba
