### ISSUE TITLE
Van's Car hírdetőtáblák berakása

### ISSUE THREAD

**Issue by Tibi5D** [hlgamesystem/hlmta_public#42]
### Írd le részletesen a hibát

GOV elbírálta és a Van's Car kifizette már az igénylést ( https://forum.hl-rpg.eu/threads/van-s-car-hirdetotabla-igenylese.61361/ ).
Xenius kérésére github-ra rakom már egy ideje a táblákat, és nem fórumra.
Előre is köszönik.
Lentebb mellékelem a pozíciókat.
Dizájn elérése: https://forum.hl-rpg.eu/threads/van-s-car-hirdetotabla-igenylese.61361/

### Reprodukálás lépései

-

### Egyéb információk

Pozíciók/azonosítók:
- [x] 1. 1800.3742675781, 2162.869140625, 10.418378829956
- [x] 2. 1723.6898193359, 2488.1557617188, 6.4336094856262
- [x] 3. 2150.0544433594, 2582.5270996094, 6.3720149993896
- [x] 4. 2150.0544433594, 2582.5270996094, 6.3720149993896 (másik oldal.)
- [x] 5. 2610.8010253906, 2544.5458984375, 5.4064898490906
- [x] 6. 37/1. tábla.
- [x] 7. 38/1. tábla.
- [x] 8. 2731.2587890625, 1616.7537841797, 6.3321452140808
- [x] 9. 39/2. tábla.
- [x] 10. 2708.3073730469, 954.23626708984, 10.266841888428
- [x] 11. 2708.3073730469, 954.23626708984, 10.266841888428 (másik oldal.)
- [x] 12. 41/2. tábla.
- [x] 13. 42/2. tábla.
- [x] 14. -2157.9765625, -452.90338134766, 34.940837860107
- [x] 15. -2198.1872558594, -411.55639648438, 34.932891845703
- [ ] 16. 482.13095092773, -1282.3403320312, 15.126411437988
- [x] 17. 30/1. tábla.
- [x] 18. 33/1. tábla.
- [x] 19. 949.61114501953, -1239.0086669922, 16.114267349243
- [x] 20. 1648.9326171875, -1793.2530517578, 13.133871078491
- [x] 21. 2767.9729003906, -2175.3764648438, 10.590354919434
- [x] 22. 35/1. tábla.
- [x] 23. 2503.7250976562, -1348.9405517578, 29.12414932251
- [x] 24. 2105.9001464844, -959.32214355469, 53.998287200928
- [x] 25. 1579.8198242188, -888.77630615234, 50.685935974121
- [x] 26. 1782.0233154297, 1075.0926513672, 6.3588943481445
- [x] 27. 1782.9259033203, 1474.2980957031, 6.3374242782593
- [x] 28. 1782.9278564453, 1793.1773681641, 6.3362469673157
- [x] 29. 1782.1633300781, 1976.853515625, 4.6645407676697
- [x] 30. 1807.6695556641, 2061.4514160156, 10.574496269226

### Log

```shell
-
```

**Comment by Tibi5D** [comment]
Tudom hogy ez hibajelentésként funkcionál, de nem igazán találtam a másik opciót jobbnak, hogy oda rakjam ezt.

**Comment by Xenius97** [comment]
16-os nem megoldható, modellezés

**Comment by Xenius97** [comment]
Ki is kerültek mert elvették az autókert
