### ISSUE TITLE
Horizon hirdetőtáblák

### ISSUE THREAD

**Issue by Tibi5D** [hlgamesystem/hlmta_public#44]
### Írd le részletesen a hibát

Nem hiba, de erre nem engedte kiválasztani a múltkori "labelt".
Hirdetőtáblák kordinátái/azonosítói:
1. Elvileg textúra és nem lehet.
2. 1690.4948730469, -1174.9254150391, 68.432632446289
3. 1223.44140625, -1133.1604003906, 49.280151367188
4. 30/1
5. 412.45648193359, -1310.6469726562, 46.001598358154
6. 2431.6450195312, -1398.9832763672, 39.600215911865
7.  600.42633056641, -1510.7265625, 34.278385162354
8. 1877.7161865234, -1550.4683837891, 39.732200622559
9. 1438.1252441406, -1291.2506103516, 46.802062988281
10. 1581.400390625, -1170.8974609375, 64.942848205566
11. 2709.7678222656, 957.39758300781, 40.591323852539
12. 2709.9931640625, 1493.185546875, 34.883056640625
13. 2736.283203125, 1615.8236083984, 31.630403518677
14. 38/1
15. 37/1
16. 2622.5900878906, 2543.0935058594, 32.870670318604
17. 45
18. 44
19. 29/6
20. -2013.3112792969, 344.88989257812, 60.358856201172
21. -2144.0380859375, -370.93829345703, 56.421131134033
22. -2061.6625976562, -328.62710571289, 57.288375854492
23. 8/1
24. 9/2
25. 41/2
26 42/2

### Reprodukálás lépései

-

### Egyéb információk

Fórum topic: https://forum.hl-rpg.eu/threads/horizon-news-hirdetotabla-igenyles.61751/
Hirdetőtáblák képen: https://imgur.com/a/E0IUlQW#931WyZr
Dizájn: https://imgur.com/Rhy3f2m

### Log

```shell
-
```

**Comment by Tibi5D** [comment]
Upsz, most találtam meg a jó helyet neki éppen, elnézést. Legközelebb oda nyitom majd.

**Comment by Xenius97** [comment]
5. sem lehet
