### ISSUE TITLE
Farm Bug.

### ISSUE THREAD

**Issue by Csabys21** [hlgamesystem/hlmta_public#49]
### Írd le részletesen a hibát

A  2023.02.04 es szero restartal a farmok nagyrésze lerohadt/resetelődött s újra eladóvá vált.
Így járt a haverom is. Ic neve Kevin Murdock, én csak rohadt farmot kaptam kézhez.

### Reprodukálás lépései

???

### Egyéb információk

Remélem minél hamarabb kilesz javítva s visszakapom a régi állapotot.Forumon is várható lesz nagy mennyiségbe.

### Log

```shell
Nincs
```

**Comment by Xenius97** [comment]
Szia, a farmot nem tudom már visszaadni így egy összegben kell megállapodjunk, mi az ami neked megfelelne? Mennyit áldoztál rá?

**Comment by Xenius97** [comment]
válasz hiányában zárom
