### ISSUE TITLE
Nem nőnek a növények pénteken szabaddá vált farmokon/állapotjelző hiba.

### ISSUE THREAD

**Issue by eth3301** [hlgamesystem/hlmta_public#5]
### Írd le részletesen a hibát

Tegnap megvásárlásra került pár szabaddá vált farm, az összes farm először ásva, utána öntözve lett. Utána miután megtettem ezt a többivel is, ültettem paradicsomot reggel 5-6 óra felé. Most délutánra maga a növény "nő" külsőleg, de az állapotjelző üres.

Egyik ismerősömnél is ez a probléma áll fent, ők tegnap este tíz felé tették meg ezeket a lépéseket. 

(#5) 06:48: 
![mta-screen_2022-11-05_06-48-45](https://user-images.githubusercontent.com/70336188/200125746-3efa5f32-7b02-4954-a8bf-a4ab13d19ff3.png)

(#5) 15:44:
![mta-screen_2022-11-05_15-44-52](https://user-images.githubusercontent.com/70336188/200125763-7115f52e-1d9b-410d-af64-2a8ff0f5d820.png)

Példa farm: Bluberry Alsó: (#5,#40,#41)

### Reprodukálás lépései

Előző tulajos automata eladás.
Ásás,öntözés.
Ültetés.

### Egyéb információk

Még a bejövetelkör vásárolt farmok nőnek, működnek.
Az ajtó zárásos hibához nem lesz köze szerintem, mert van olyan farm ahol működik rendesen a nyitás, ott sem nő az állapotjelző. #4 
Kérésre tudok csatolni több képet.

### Log

```shell
clientscript nem dob semmit.
```

**Comment by eth3301** [comment]
Update:
A nővények nőnek, az állapotjelzővel van gond addig ameddig el nem éri a növény teljes kifejlődöttségét (50%) onnantól normálisan mutatja a csíkot.

**Comment by SteveScott77** [comment]
Javítva lett. (más már jelentette előbb)
