### ISSUE TITLE
Le rohadt 8db nagy farm.

### ISSUE THREAD

**Issue by kismokesz** [hlgamesystem/hlmta_public#50]
### Írd le részletesen a hibát

A videón szereplő 8db farm tegnap lett beültetve ami azt jelenti hogy 5 napig termett volna és 4080 pari ment a levesbe, kérném szépen a paradicsomok és nem készpénzt. 

### Reprodukálás lépései

Nincs amivel reprodukálni lehetne.

### Egyéb információk

Remélem megoldható hogy a parikat kapjam visza és ne a készpénzt, mivel a parik nekem többet jelentenek.

### Log

```shell
https://www.youtube.com/watch?v=DGKRTUrBQvI
```

**Comment by Xenius97** [comment]
Szia, a farmot nem tudom már visszaadni így egy összegben kell megállapodjunk, mi az ami neked megfelelne? Mennyit áldoztál rá?

**Comment by kismokesz** [comment]
Hello, itt le rohadtak a paradicsomok, azokat tudsz adni?

**Comment by Xenius97** [comment]
Odaadtam, ha nem találod akkor tárgy visszaigénylés
