### ISSUE TITLE
9db nagy farmomon a termés kirohadt, tegnap este meglettek locsolva.

### ISSUE THREAD

**Issue by kismokesz** [hlgamesystem/hlmta_public#51]
### Írd le részletesen a hibát

Előre is köszönöm szépen, 918 pari, szintén jobban örülnék ha parit kapnék.

### Reprodukálás lépései

Nincs amivel reprikálható.

### Log

```shell
itt a 8db videó: https://www.youtube.com/watch?v=To73DlE8Wbk&embeds_euri=https%3A%2F%2Fforum.hl-rpg.eu%2F&source_ve_path=MTM5MTE3&feature=emb_logo

itt a másik telepen lévő: https://www.youtube.com/watch?v=ODteSSXfY3g
```

**Comment by Xenius97** [comment]
Szia, a farmot nem tudom már visszaadni így egy összegben kell megállapodjunk, mi az ami neked megfelelne? Mennyit áldoztál rá?

**Comment by kismokesz** [comment]
Hello, itt le rohadtak a paradicsomok, azokat tudsz adni?

**Comment by Xenius97** [comment]
megoldva
