### ISSUE TITLE
2db nagy farm le bugolt a nevemről.

### ISSUE THREAD

**Issue by kismokesz** [hlgamesystem/hlmta_public#52]
### Írd le részletesen a hibát

A 181 és 381-es nagy farmokról lenne szó.

A 181-es még január 10-re bugolt le a nevemről.

A 381-es január 27-re bugolt le.

### Reprodukálás lépései

Nincs.

### Log

```shell
181 bizonyiték: https://imgur.com/a/gHrXJlh#WFepYet

381 bizonyiték: [2023-01-26 22:00:26] [Output] : [HL - Farm (ID: 381)]: A farmod 5 nap 10 óra 33 perc 23 másodperc múlva le fog járni.
```

**Comment by Xenius97** [comment]
Szia, a farmot nem tudom már visszaadni így egy összegben kell megállapodjunk, mi az ami neked megfelelne? Mennyit áldoztál rá?

**Comment by kismokesz** [comment]
Hello, slagal szereltek, tele voltak trágyával, illetve kéztől vásárolt farmok voltak, 5 millió a 2 farmra megfelelne?

**Comment by Xenius97** [comment]
megoldva
