### ISSUE TITLE
Pizzafutár nyereményjátékot nem számolja.

### ISSUE THREAD

**Issue by Nektarin1** [hlgamesystem/hlmta_public#53]
### Írd le részletesen a hibát

Ha kiszállítok egy pizzát, nem számolja azt. Teszteltem SA styleon, és ott jól működött.
https://imgur.com/a/v8RISDO

### Reprodukálás lépései

-

### Egyéb információk

-

### Log

```shell
-
```

**Comment by Xenius97** [comment]
Szia, javítottam ha most sem lenne jó nyisd újra.
