### ISSUE TITLE
Alkohol érlelés BUG

### ISSUE THREAD

**Issue by dawve22** [hlgamesystem/hlmta_public#55]
### Írd le részletesen a hibát

Alkoholfőzésnél lenne a hiba. Van x mennyiségű érlelt pálinkám de ugyanannyiba kerül a piaci ára mint a frissen érlelt (1 napos) pálinka. Eladásnál se változik az ár tehát ugyanannyit kapok érte.

### Reprodukálás lépései

1. Tároló megnyitása
2. Több napos érlelés megvárása
3. A piaci érték nem változik...

### Egyéb információk

Gondolom azért van lehetőség az érlelésre mivel akkor többet ér az adott alkohol.

### Log

```shell
Ezen a képen látható minden aminek látszódnia kell: 
https://imgur.com/a/1tF3Hee
```

**Comment by Xenius97** [comment]
Csak a whiskey érlelődik.
