### ISSUE TITLE
Item duplikálodás bug.

### ISSUE THREAD

**Issue by kismokesz** [hlgamesystem/hlmta_public#56]
### Írd le részletesen a hibát

Hello

Xenius köszöntem az elözö bugok miatti segitséget, most egy olyan lenne hogy ami nállam van mindenből dupla lett most hogy felléptem, illetve visza igénylések alatt is vannak bőven amiből vannak nállam, igényeljem visza egyenként és dobjam ki őket vagy eltudod rendezni hogy elvedd őket?

https://imgur.com/a/qI3sQWH

### Reprodukálás lépései

-

**Comment by Xenius97** [comment]
Szia, megoldódott most inventory restart után?

**Comment by kismokesz** [comment]
Köszöntem szépen igen meg :)
