### ISSUE TITLE
Tapéta

### ISSUE THREAD

**Issue by tonycolt** [hlgamesystem/hlmta_public#6]
### Írd le részletesen a hibát

Még mindig nem működik a tapéta felrakása. Nem jelenik meg a választó menü, hogy hova szeretném felrakni.
Link beírása működik a tapétára., csak a felhelyezés nem.

### Reprodukálás lépései

1. Írd be a kiválasztott tapétára a kép linkjét.
2. Mentsd el.
3. Húzd ki az inventoryból a falra.
4. Nem történik semmi.

**Comment by bence444** [comment]
Nem ki kell húzni, miután beállítod a linket jobb klikk az itemre és használat
![kép](https://user-images.githubusercontent.com/24188992/201324519-28bbc28a-4c02-40de-a83a-72025b4b1ee7.png)

**Comment by tonycolt** [comment]
> Nem ki kell húzni, miután beállítod a linket jobb klikk az itemre és használat ![kép](https://user-images.githubusercontent.com/24188992/201324519-28bbc28a-4c02-40de-a83a-72025b4b1ee7.png)

Ja bocsi. Jött erről valami infó? Eddig húzni kellett. De mindegy is. Szóval működik. Remek. Köszi🙂

**Comment by bence444** [comment]
changelog
![kép](https://user-images.githubusercontent.com/24188992/201327427-2b3aee7d-6fce-4910-95b5-d5425e50f52a.png)
