### ISSUE TITLE
Oliveria Car Co. hirdetőtáblák

### ISSUE THREAD

**Issue by Tibi5D** [hlgamesystem/hlmta_public#61]
### A funkció iránti kérésed problémához kapcsolódik? Kérlek írd le.

Oliveria Car Co. hirdetőtáblákat kellene betölteni.
https://forum.hl-rpg.eu/threads/oliveria-car-co-hirdetotabla-igenylesi-kerelme.68182/

Dizájn: https://imgur.com/abwq2je
Helyszínek: https://imgur.com/a/kyaXEf2#ZfdF8CC

### Írd le a kívánt megoldást

-

### Egyéb információk

-

### Megerősítés

- [X] Kijelentem, hogy a fent említett javaslat fórumon elbírálásra került, vagy Tulajdonosi engedéllyel rendelkezem.

**Comment by Xenius97** [comment]
Ha még aktuális akkor nyisd újra
