### ISSUE TITLE
Volkswagen Caddy rekesz és vegyi bővítés

### ISSUE THREAD

**Issue by tonycolt** [hlgamesystem/hlmta_public#62]
### Írd le részletesen a hibát

Szisztok!

Nem lehet rekeszt és vegyi bővítést eszközölni az új volkswagen caddyben.
Csak 5 csomagot enged szállítani.

### Reprodukálás lépései

Tuningolóban nincs ilyen opció.

**Comment by Xenius97** [comment]
Nincs rekeszbővítés, vegyi cucc a caddyre
