### ISSUE TITLE
Mercedes Sprinter és Ford Explorer kézi villogó nem feltehető. [LSPD,SFSD,FBI]

### ISSUE THREAD

**Issue by TetsuDev** [hlgamesystem/hlmta_public#64]
### Írd le részletesen a hibát

A modellcserék óta (Ford Transit --> Mercedes Sprinter) és (Chevrolet Tahoe --> Ford Explorer) nem lehet feltenni a kézi villogót a járművekre. 
A civil jelöletlen autóknak így jelenleg most nem tudjuk hasznát venni.

### Reprodukálás lépései

Be kell ülni egy frakciós autóba, villogó itemmel.
Inventoryba ha rákattintunk az itemre és a használatra akkor nem történik semmi.

**Comment by Xenius97** [comment]
Áthelyezve, https://github.com/hlgamesystem/hlmta/issues/881
