### ISSUE TITLE
Álnév hiba. [LSPD,SFSD,FBI]

### ISSUE THREAD

**Issue by TetsuDev** [hlgamesystem/hlmta_public#65]
### Írd le részletesen a hibát

Amennyiben kifagyunk álnév használata közben, a dashboardban (frakció panelban) ott marad az álnév, nem vált vissza mint a fej feletti név az eredeti névre.

### Reprodukálás lépései

Állítsuk be az álnevet a parancs használatával.
Fagyjunk ki a szerverről, miközbe bevan kapcsolva az álnév.

**Comment by Xenius97** [comment]
Áthelyezve, https://github.com/hlgamesystem/hlmta/issues/881
