### ISSUE TITLE
Detektív Szolgálat Permission ( /duty detective ) [LSPD,SFSD,FBI]

### ISSUE THREAD

**Issue by TetsuDev** [hlgamesystem/hlmta_public#66]
### Írd le részletesen a hibát

Egyeztettem jack-el, a probléma valószínűleg az hogy régen rang szinthez volt állítva, például 13-as rang.
Most pedig pipálható jog, viszont hiába van kipipálva, ha kissebb rangon próbálom meg mint amire bevolt állítva régen akkor nem működik.

### Reprodukálás lépései

1. Vedd be az embert frakció panelba.
2. Tedd egy olyan rangra amin bevan állítva a duty detective. PL: 2-es rang, az biztos hogy kicsi a régi rendszerhez képest.
3. Próbáld ki a /duty detective parancsot.

**Comment by Xenius97** [comment]
Áthelyezve, https://github.com/hlgamesystem/hlmta/issues/881
