### ISSUE TITLE
Vállalkozás bolt beragadt rendelés

### ISSUE THREAD

**Issue by tonycolt** [hlgamesystem/hlmta_public#7]
### Írd le részletesen a hibát

Sziasztok!

Már múltkor is előfordult, hogy beragadt egy rendelés a boltomban, mikor szállítás közben kifagytam.
Most egyik alkalmazottam fagyott ki és nem tudok ezzel a szállítás alatt lévővel mit kezdeni.
Sem törölni nem lehet, sem pedig újrakezdeni, de még további árut rendelni sem. Ilyenkor a CP -k is eltűnnek.
Múltkor 5 napig nem tudtam használni emiatt a boltom. Légyszíves javítsátok, mert ez így elég bosszantó, főleg hogy mostanában sokan panaszkodnak hogy gyakran kifagynak. 6028 -as iroda.

Volt már erről bejelentésem, most ugyanaz a hiba. Az alábbi linken megtekinthető.

https://forum.hl-rpg.eu/threads/vallalkozas-bolt-beragadt-rendeles.57699/

Illetve másoknál is előfordult:

https://forum.hl-rpg.eu/threads/beragadt-szallitas.58580/
https://forum.hl-rpg.eu/threads/boltomba-beragadt-a-rendeles.58299/
https://forum.hl-rpg.eu/threads/benzinkut-vallalkozas-hibajelentes.57394/

U.i.: Van ott egy dátum is, hogy meddig lehet átvenni az árut, de a lejárat napján sem történt semmi változás, csak 5 nap után írta ki, hogy a rendelés lejárt és akkor engedte törölni.

### Reprodukálás lépései

1. Nyisd meg az irodában a számítógépet.
2. Menj  a rendelések ikonra.
3. Ott látható a szállítás alatt lévő sor.
4. Próbálj meg bármit kezdeni vele.
5. Menj a HL Marketre és próbálj meg valamilyen rendelést leadni. Azt sem engedi.

### Egyéb információk

Lehessen valahogy újrakezdeni a szállítást, ha kifagyok, vagy az alkalmazottam kifagy legyen újra aktív a szállításra kész szöveg. 

Azóta van így hogy downgrade -elni kellett. Vagy amióta a farm bejött a szerverre kb. Azelőtt ha kifagytam, akkor visszajöttem és a szállítás alatt szöveg szállításra készre visszaállt és el tudtam kezdeni újból. Ez is bosszantó, de működött.

Előre is köszönöm!

**Comment by Xenius97** [comment]
Szia javítottam rá tudnál nézni?

**Comment by tonycolt** [comment]
> Szia javítottam rá tudnál nézni?

Szia. Most azt írta szállítás sikertelen és ki tudtam törölni. Kipróbálom, hogy rendelek valamit és kilépek szállítás közben, hogy akkor újra tudom -e kezdeni, mert az lenne a cél. Ezelőtt így volt és nem volt gond. Jelentkezek nemsokára.

**Comment by tonycolt** [comment]
> Szia javítottam rá tudnál nézni?

Na kipróbáltam. Elindítottam egy szállítást és bezártam az MTA -t. Visszajöttem és azt írja megint, hogy "szállítás alatt". Ilyenkor kellene visszaállniaarra, hogy "szállításra kész", hogy el tudjam kezdeni újra. Még így sem jó.

**Comment by tonycolt** [comment]
Valahogy azt kellene elérni szerintem, hogy amíg szállítás alatt van egy rendelés addig ne mentse a rendszer. Ha kifagysz utána ugyanúgy maradjon, mintha el sem kezdted volna. Azt nem tudom, mi van akkor ha elvállalsz egy kiszállítást és kifagysz akkor mi történik az áruval amit viszel, mert olyan még nem volt, de sanszos, hogy azt is levonja az árukészletedből. Szóval itt a mentésekkel lesz gond.

**Comment by SteveScott77** [comment]
Megoldva. Ugyanúgy fog működni, ahogyan eddig. Ha leléptek, akkor reseteli szállításra készre. Bekerült egyik updatekor valami, aminek megakasztotta, ez okozta, hogy egyik napról a másikra jelentkezett a probléma. Mai nap betöltöm.
